# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: googleapis/python-multi:latest
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: 666666
        ports:
          - 3306:3306
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_PASSWORD: 666666
        ports:
          - 5432:5432

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Run tests - opencensus
          command: |
            pip install --upgrade nox
            nox -f noxfile.py -s sqlite_check
      - deploy:
          name: Push to PyPI (if this is a release tag).
          command: scripts/twine_upload.sh

deployment:
  tag_build_for_cci2:
    branch: /v([0-9]+)\.([0-9]+)\.([0-9]+)/
    tag: /v([0-9]+)\.([0-9]+)\.([0-9]+)/
    commands:
      - true
